### ISSUE TITLE
branch with / not populating

### ISSUE THREAD

**Issue by justbill2020** [schme16/gitcdn.xyz#13]
branch: jb/hotfix-510 will not populate
raw: https://raw.githubusercontent.com/evancohen/smart-mirror/jb/hotfix-510/plugins/_general/config.schema.json
gitcdn: https://gitcdn.xyz/repo/evancohen/smart-mirror/jb/hotfix-510/plugins/_general/config.schema.json
when i right click on the url for gitcdn and click "go to https://gitcdn......" it changes url to https://gitcdn.xyz/cdn/evancohen/smart-mirror/041e633100d9d3a194886693c51e01dc4359748c/hotfix-510/plugins/_general/config.schema.json and gives a 404 error.

**Comment by schme16** [comment]
Thanks for the report, I'll look into it ASAP!

**Comment by justbill2020** [comment]
Any updates on this one?

**Comment by justbill2020** [comment]
@schme16,

ok so i noticed that when it gives me the redirected url it changes `repo` to `cdn`.... so when i changed it to `cdn` it works on both links to the master branch and other branches even those with a `/` within the url... 

I think updating the docs a bit would help... possibly even removing the repo and only having cdn as well... not sure if this is expected behavior or not... but for now i'm closing this
