### ISSUE TITLE
Not redirect http requests to https?

### ISSUE THREAD

**Issue by javier-lopez** [schme16/gitcdn.xyz#2]
Hi,

First of all thanks for gitcdn =), it's good to have several options from where to choice, I wonder if there is any chance to avoid auto redirecting http request to https?, or to get an option to avoid this redirection, on Rawgit this is only possible using the CDN option, eg.

busybox wget http://cdn.rawgit.com/minos-org/minos-static/d1a24fb18a7e6236f8e99728bbedd82df297c3c7/static-get

**Comment by schme16** [comment]
@chilicuil: Hey, thanks for the heads up!
As I was designing the system, I decided to go https only to save myself some trouble (there's a little weirdness with how KeyCDN + Cloudflare tell me what protocol the user requested), and decided it probably wasn't an issue, haha.

Now that I know there's someone bumping up against this problem, I'll get it cleared up asap! 
Feel free to submit a pull request in the meantime, if you'd like!
