### ISSUE TITLE
URL cache

### ISSUE THREAD

**Issue by vitorcoxta** [schme16/gitcdn.xyz#20]
Hi,

This is not really an issue, but rather a question: how does the URL cache really works, and how often or is (or should be) updated? Because I'm using the URL as follows:

`https://min.gitcdn.xyz/repo/<username>/<project>/master/<file>`

but this URL doesn't update as often as I thought it would... From my understanding in the docs, this should look for the latest commit every ~2h, but it is still pointing to an older commit for several days now...

Thanks in advance!

**Comment by Memnarch** [comment]
had the same issue a year ago: https://github.com/schme16/gitcdn.xyz/issues/12
Seems the thing with latest commit isn't actually working.

**Comment by FuriosoJack** [comment]
Tengo el mismo problema

**Comment by schme16** [comment]
Hey all, as per https://github.com/schme16/gitcdn.xyz/issues/12#issuecomment-447754208, the min subdomain isn't really designed for "always up to date". (hence why I've not got it officially documented in the README). At present only the standard gitcdn will update frequently.
