### ISSUE TITLE
CSS file now forbidden.

### ISSUE THREAD

**Issue by Yerren** [schme16/gitcdn.xyz#25]
Hey! :)

I've been using gitCDN for a small project for a few months now and it has been great so far!
However, suddenly a CSS file which the project fetches using gitCDN no longer works, and I get the message that it is forbidden.

I'm not sure if I have somehow misused the system to end up with this file blocked, but I would be very happy to change things if I know what has gone wrong!

This is the link to the [Repo in question](https://github.com/Yerren/FreshWDL) and this is the particular [file which is blocked](https://github.com/Yerren/FreshWDL/blob/master/css/stylesheet01.css).

I really hope that we can fix whatever has happened here, as I have truly found gitCDN great!
Thanks in advance!

Edit: Under extra inspection, I may not have been using the right URL for my job (a /repo/ instead of /cdn/ in there). I apologise for that, and hopefully you can confirm that this was in fact the issue and that there is nothing more I need to fix up. If there is, however, I am happy to work it out!

**Comment by schme16** [comment]
Hmm, that shouldn't have been causing you to get blocked; the system auto blocks files that return errors multiple tries in a row. i.e. 404, 403, 500, etc.
Can you post the link you've been using so I can make sure it wasn't flagging false positives?

In the mean time I've cleared the temp blocks, which should clear your issue too (https://gitcdn.xyz/repo/Yerren/FreshWDL/master/css/stylesheet01.css seems to work as intended now)

**Comment by Yerren** [comment]
Thank you, it's much appreciated!

I can't give you much more than the the actual link you gave me (https://gitcdn.xyz/repo/Yerren/FreshWDL/master/css/stylesheet01.css), as the site using it already changed to using /cdn/.

If there is anything else I can get you to help you out, just let me know!
