### ISSUE TITLE
Appeal:  this repo/gist is on the blacklist

### ISSUE THREAD

**Issue by tchaffee** [schme16/gitcdn.xyz#26]
Users are getting this message when trying to access our file from this CDN:

```
Forbidden - This repo/gist is on the blacklist. If you wish to appeal, please open an issue here: https://github.com/schme16/gitcdn.xyz/issues, with why you feel this repo should not be on the blacklist.
```

I'm not sure how we got on the blacklist, but we are using this CDN to serve our bundle for a legit project which is part of the freeCodeCamp offering which is one of the most popular open source repositories on github.

Our repo is https://github.com/freeCodeCamp/testable-projects-fcc

**Comment by agamemnus** [comment]
Same here.

**Comment by ThibautSF** [comment]
Another Example : https://gitcdn.xyz/repo/Zerthox/ClearVision/master/css/ClearVision_v5.min.css

**Comment by Flerex** [comment]
I also got my repository banned and I don't understand why. https://gitcdn.xyz/repo/Flerex/cdn/master/fm/recent-topics-generator.js

**Comment by Urahara** [comment]
Same. https://gitcdn.link/repo/peppercharm/ptp-raise/master/raise.min.css

**Comment by phit** [comment]
Same https://gitcdn.xyz/repo/phit/discord-maroon-theme/master/style.css

**Comment by hieuhuynh93** [comment]
Same https://gitcdn.link/repo/wintercounter/Protip/master/protip.min.css

**Comment by trustless-zz** [comment]
Yup https://gitcdn.xyz/repo/trustless-zz/elephant/master/elephant.css

**Comment by schme16** [comment]
I'm on the Australian cloudflare ray (Sydney) and all of the gitcdn links listed above are directing to their respective files correctly.

I've done a master level purge on both domain names in the hopes it clears this up, but anyone still having this issues please post back with the link that's not working still!

**Comment by schme16** [comment]
Looks like this issues should be sorted- closing off
