### ISSUE TITLE
Discord Theme CSS Blacklisted

### ISSUE THREAD

**Issue by pokeacer** [schme16/gitcdn.xyz#27]
https://gitcdn.xyz/repo/SamuiNe/Crystalline-css/master/crystalline.css has been blacklisted; it's a Discord Theme used for BeautifulDiscord, so it's  broken for quite a few people right now

**Comment by schme16** [comment]
I'm not able to replicate this; clicking the link takes me directly to the file- I'll do a CDN purge and see if that sorts your region out!

**Comment by pokeacer** [comment]
Works fine now from my end; thanks!

**Comment by schme16** [comment]
Awesome!
