### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by wintercounter** [schme16/gitcdn.xyz#3]
Hi, I have error with this one:
`https://gitcdn.xyz/repo/sindresorhus/github-markdown-css/gh-pages/github-markdown.css`
I have other files from gitcdn too, they are working fine.

**Comment by schme16** [comment]
Hey @wintercounter: I knew this bug would bite me in the butt sooner or later!
What's happening is that the gitcdn server looks for the latest commit in the repo; problem is that it currently looks for that in the branch `master` -_-;

I'll make the effort and fix this, like I should have months ago...

**Comment by aatishb** [comment]
Hi there, I'm having the same error after my latest commit, even though the commit was to the master branch.

https://gitcdn.xyz/repo/aatishb/drape/master/index.html
