### ISSUE TITLE
Link is not updating since 22 hours

### ISSUE THREAD

**Issue by kirayoru** [schme16/gitcdn.xyz#30]
Everything worked but since last update I pushed 22 hours ago, link is not updating.
https://gitcdn.xyz/repo/kirayoru/PlayfulPandaTheme/master/ppmain.css

**Comment by schme16** [comment]
see: #29 
Should be sorted out now, the TL;DR is that it seems to be a browser caching issue- I've altered Cloudflare's settings and cleared all the cache's I control (i.e. all but you browser), after a cache clear it should be all good
