### ISSUE TITLE
open source repo blacklisted, our tool no longer works

### ISSUE THREAD

**Issue by sdetweil** [schme16/gitcdn.xyz#38]
our opensource project uses 
repo/joshfire/jsonform/

which is suddenly blacklisted. 

our tool no longer works.. 

please remove the blacklist, and provide info on the cause (not our code)

**Comment by Flerex** [comment]
Same here for https://gitcdn.xyz/repo/Flerex/cdn/master/fm/custom-profile.js

It happened to me a few months ago. Is it my fault?

**Comment by schme16** [comment]
I've cleared both from the temp blacklist, they should work again now.

The way the system decides a black list is if the file you're trying to use returns a 404, as 404 (file not found) isn't a good thing to cache, neither the server, CloudFlare, nor GitHub will cache it, and GitHub will actively punish my server (by restricting how much I can request for a little while) when too many 404's are requested too quickly from one repository.

Hope that sheds some light!

**Comment by sdetweil** [comment]
thanks very helpful...

but many of us use this and I suspect new developers are adding new consumers, and some will get the spelling wrong, causing the 404 and they will cause more blacklist events for us all.
