### ISSUE TITLE
Most all requests are returning 503

### ISSUE THREAD

**Issue by Splaktar** [schme16/gitcdn.xyz#42]
Visit https://gitcdn.link/
```
base.css:1 Failed to load resource: the server responded with a status of 503 ()
clipboard.js:1 Failed to load resource: the server responded with a status of 503 ()
/sys/js/url-formatter.js:1 Failed to load resource: the server responded with a status of 503 ()
/favicon.ico:1 Failed to load resource: the server responded with a status of 503 ()
base.css:1 Failed to load resource: the server responded with a status of 503 ()
```

Same issue for AngularJS Material CodePen resource URLs:
- https://cdn.gitcdn.link/cdn/angular/bower-material/v1.1.10-master-0671aab/angular-material.js
- https://cdn.gitcdn.link/cdn/angular/bower-material/v1.1.10-master-0671aab/angular-material.css
```
index.html:4 GET https://cdn.gitcdn.link/cdn/angular/bower-material/v1.1.10-master-0671aab/angular-material.css net::ERR_ABORTED 503
```

![screen shot 2018-09-30 at 2 52 12 pm](https://user-images.githubusercontent.com/3506071/46261360-74f86180-c4c0-11e8-852b-f50c64ac06f1.png)

Tried to use gitcdn.xyz as a workaround, but these also 503:
- https://cdn.gitcdn.xyz/cdn/angular/bower-material/v1.1.10-master-0671aab/angular-material.js
- https://gitcdn.xyz/cdn/angular/bower-material/v1.1.10-master-0671aab/angular-material.js

**Comment by schme16** [comment]
thanks for the report! It looks like a transient outage (the logs don't reveal much)- I've set up a more aggressive watchdog on the server until I can pinpoint what caused it!

It's all back up as of now though

**Comment by Splaktar** [comment]
Yep, it does seem to be working properly now. Thank you!
