### ISSUE TITLE
Missing charset in content-type HTTP header

### ISSUE THREAD

**Issue by fasttime** [schme16/gitcdn.xyz#43]
I noticed that some JavaScript files look garbled when viewed directly in the browser via a GitCDN URL. Compare for instance

https://rawgit.com/muan/emoji/gh-pages/javascripts/emojilib/index.js (looks OK)

with

https://gitcdn.xyz/repo/muan/emoji/gh-pages/javascripts/emojilib/index.js (garbled)

Apparently GitCDN is not adding `charset=utf-8` on content-type headers when serving JS files, and that causes browsers to display those files as if they were ISO-8859-1 encoded. Of course, that's not a problem when the files are loaded in a HTML page, it just looks silly to developers who look at them.

I was wondering if there is a way we can get the UTF-8 charset added. Other CDNs I'm aware of (RawGit, raw.githack.com, Staticaly, etc.) do that already.

**Comment by schme16** [comment]
Aaaaaaannnnnddddd Done: 1e00bfbf6fce5e075fad0d40f9532d1d7be9eff0

**Comment by fasttime** [comment]
Looks perfect now. Great job!
