### ISSUE TITLE
Could you include "https://gist.github.com" ?

### ISSUE THREAD

**Issue by mikhoul** [schme16/gitcdn.xyz#46]
Could you include "https://gist.github.com" also ?

Regards :octocat:

**Comment by mikhoul** [comment]
An updade since @schme16  did not answer.

The reason I wanted to use a Gist is because I have some code I use that I don't want to make it fully public so I use a secret Gist which is enough for me.

So today I looked in the code of gitcdn.xyz and I have seen that in fact GithubGist work :smile:  but the GUI at https://gitcdn.xyz/ was never updated to generate the URL from GithubGist.

Here's the file that @schme16 will need to update to generate links for Gist.

So until the GUI will be updated you have to generate the URL manually so here's an exemple: 

https://gist.github.com/mikhoul/41122d22b9e731400b164a3ed8344d8e/raw/6b91e6bed5f892e29a72ff4f9e8538c5c501d88a/YouTubeCenterHacked.user.js

Will become:
https://gitcdn.xyz/repo/mikhoul/41122d22b9e731400b164a3ed8344d8e/raw/6b91e6bed5f892e29a72ff4f9e8538c5c501d88a/YouTubeCenterHacked.user.js


Here's a Userscript I've done that I will update in the next days to generate a button on gist.github.com  to have the link generated automatically: https://greasyfork.org/en/scripts/373361-github-gitcdn-button

![image](https://user-images.githubusercontent.com/5678673/50183207-5f385280-02df-11e9-97ef-2f948fad69e6.png)


Regards :octocat:

**Comment by mikhoul** [comment]
I updated my previous post for the format of the URL since the URL manually generated was pointing to a specific revision of the file and not the latest revision.

**Comment by schme16** [comment]
Adding this feautre to the 2.0.0 milestone

**Comment by schme16** [comment]
@mikhoul: I skimmed the message while compiling a list of todos for 2.0.0, and didn't ever take in how awesome your work was!
I know that you've moved to supporting another service, but I'd still like to thank you for the time you took to do this (regardless of if it's still being maintained.)


The server re-write for 2.0.0 has sorted out the inital problem that this issue brought up.
closing off for now
