### ISSUE TITLE
Support "pseudo HTTP parameters" , e.g. https://gitcdn.xyz/repo/user/repo/page.html?param=value

### ISSUE THREAD

**Issue by jmvanel** [schme16/gitcdn.xyz#48]
What I call "pseudo HTTP parameters" (maybe there is a better naming ?) are parameters in URL that look like regular HTTP parameters, but since the base URL is a static page, they are not interpreted by the HTTP server, but by some JavaScript code.

My real-life use case is this one :
```shell
wget --header='Accept: text/html' --debug \
  'https://gitcdn.xyz/repo/jmvanel/rdf-calendar/master/rdf-calendar.html?url=http://semantic-forms.cc:1952/ldp/1543748445108-1972318919276873'
```
I think this should not be difficult to implement :) , but I'm not a JavaScript guy .

**Comment by schme16** [comment]
I'm tentativly adding this feautre to the 2.0.0 milestone

**Comment by schme16** [comment]
See #56 
Querstring data should be fully supported now
