### ISSUE TITLE
Loading stylesheets using `crossorigin=anonymous` returns `Not Found`.

### ISSUE THREAD

**Issue by initbar** [schme16/gitcdn.xyz#5]
I've tried to load several stylesheets using `crossorigin=anonymous`:

``` css
<link rel="stylesheet" type="text/css" crossorigin="anonymous" href="https://gitcdn.xyz/repo/pseudocd/pcdn/master/stylesheets/normalize/normalize.min.css">
```

When `crossorigin=anonymous` is used, the stylesheets hits `Not Found` with `X-Cache: MISS`.

![scr](https://cloud.githubusercontent.com/assets/12630151/15126263/23b82aca-15ff-11e6-9db0-2f21641f05a0.png)

**Comment by schme16** [comment]
I can't seem to reproduce this issue (To be honest I've never even heard of `crossorigin="anonymous"`, but reading the mozilla docs about it seems to imply it's for images...).

My guess is that you're behind some sort of proxy/corporate cache, as GitCDN doesn't actually set a header called `X-Cache` (though I know many proxies/corporate caches), it uses cloudflare as the cache system, which sends a `cf-cache-status` header.

Here is what I get when trying to load it
Headers:
![image](https://cloud.githubusercontent.com/assets/116081/15305604/567cd59c-1c07-11e6-8bb5-d231a9f9967d.png)
Response:
![image](https://cloud.githubusercontent.com/assets/116081/15305613/63246832-1c07-11e6-8679-99b6fa58ac1e.png)

Both seem to be correct, but let me know if you're still experiencing issues!

**Comment by schme16** [comment]
Closing issue, but happy to re-open if problem is persists
