### ISSUE TITLE
help - my css raw is lost - 404

### ISSUE THREAD

**Issue by ShapeGroup** [schme16/gitcdn.xyz#50]
Hi ... I'm trying to upload the file but keep giving me 404 ... why?
my fault? Is there any rule that I did not understand?

https://gitcdn.xyz/cdn/ShapeGroup/kimera-frontend-framework/00a84a2f8410e27490fd1542573e18fe031475e5/deployed/latest-min-raw/core.min.css

**Comment by schme16** [comment]
Looks like over time you've changed the naming scheme on your folders, used
to be `deployed/latest min gitraw`, it's now `deployed/latest-min-raw`

Fixing that up sorts the issue out:
https://gitcdn.xyz/cdn/ShapeGroup/kimera-frontend-framework/00a84a2f8410e27490fd1542573e18fe031475e5/deployed/latest%20min%20gitraw/core.min.css

**Comment by schme16** [comment]
Looks like a simple typo, over time you've changed the naming scheme on your folders as they used
to be `deployed/latest min gitraw`, it's now `deployed/latest-min-raw`

Fixing that up sorts the issue out:
https://gitcdn.xyz/cdn/ShapeGroup/kimera-frontend-framework/00a84a2f8410e27490fd1542573e18fe031475e5/deployed/latest%20min%20gitraw/core.min.css
