### ISSUE TITLE
JSON files served as application/octet-stream

### ISSUE THREAD

**Issue by xcash** [schme16/gitcdn.xyz#51]
I have a test page for a javscript library which fetch test json files using ajax.
It is failing because gitcdn delivers json files as application/octet-stream
Why this? Are there any security related restriction?

Btw this is the test page: https://gitcdn.xyz/repo/xcash/bootstrap-autocomplete/master/dist/latest/index4.html

**Comment by schme16** [comment]
Currently GitCDN doesn't support query parameters on cached items
