### ISSUE TITLE
The whole thing is down.

### ISSUE THREAD

**Issue by agamemnus** [schme16/gitcdn.xyz#52]
https://gitcdn.link/repo/agamemnus/smoke-pure.js/gh-pages/smoke-pure.js

**Comment by agamemnus** [comment]
Well, it isn't now. Shaky.

**Comment by schme16** [comment]
Other than an outage a week ago (a GitHub cache poisoning issue), I can't
see any other issues in the logs- let me know if this happens again!

**Comment by agamemnus** [comment]
Will do and will note the time. Thanks.

**Comment by pentacular** [comment]
Seems to be down again :)
