### ISSUE TITLE
HTTP parameters in URLs cause "Application error" in gitcdn.xyz

### ISSUE THREAD

**Issue by jens-maus** [schme16/gitcdn.xyz#56]
For many years gitcdn.xyz worked flawlessly with putting even non existing URL parameters in URLs so that browser cache issues could be elegantly worked-around. Now since a few weeks/month using URL parameters seem to cause "Application errors" to be outputted.

E.g. the following gitcdn.xyz URL causes an heroku "Application error" to appear:

https://gitcdn.xyz/repo/jens-maus/RaspberryMatic/master/release/LATEST-VERSION.js?test=1

![screenshot_323](https://user-images.githubusercontent.com/5887769/63342212-36270080-c34b-11e9-83cd-0c24be721e7b.png)

However, the following same URL but without any `?XXX=YYY` parameter attached works flawlessly like before:

 https://gitcdn.xyz/repo/jens-maus/RaspberryMatic/master/release/LATEST-VERSION.js

Any help would be highly appreciated.

**Comment by schme16** [comment]
Hi Jens,
querystring parameters aren't supported on a bunch of files at the moment
(one because all data served is "static", and two Cloudflare's caching is
complex regarding querystrings)

Sorry!

**Comment by schme16** [comment]
Adding this to the 2.0.0 milestone
The 2.0.0 re-write should solve this issue

**Comment by schme16** [comment]
Querystring now supported, and no longer casue outages.
They're cached differently to their unquerystringed counterparts, so keep this in mind.
