### ISSUE TITLE
Internal Server Error for repo links

### ISSUE THREAD

**Issue by bryangingechen** [schme16/gitcdn.xyz#58]
For example: https://gitcdn.link/repo/schme16/gitcdn.xyz/master/LICENSE

and https://gitcdn.xyz/repo/schme16/gitcdn.xyz/master/LICENSE

**Comment by bryangingechen** [comment]
Seems to be working again...

**Comment by milankragujevic** [comment]
The problem is occurring again.

https://gitcdn.xyz/repo/enyo/dropzone/master/dist/min/dropzone.min.js

@bryangingechen please reopen the issue.

**Comment by forger** [comment]
Had the same issue (with a different URL) for some time today - then it went away.

**Comment by rivy** [comment]
+1 today

**Comment by natxocc** [comment]
+1 today

**Comment by theArtechnology** [comment]
+1 today

**Comment by RubyistCTRLDYT** [comment]
+1 today

**Comment by cocomine** [comment]
It happened again today

**Comment by schme16** [comment]
See #60 for more details about the why this occured, and why it's fixed now, but suffice to say that it should be occuring extreamly rarely from now on
