### ISSUE TITLE
Cache not updating

### ISSUE THREAD

**Issue by enrichman** [schme16/gitcdn.xyz#59]
I've waited for more than 4h but the content is not yet updated.
Is there a way to purge the cache?

**Comment by schme16** [comment]
Currently not that a user can control, but I'll tentatively add this to the 2.0.0 milestone and see what I can do!

**Comment by schme16** [comment]
I've re-written the server side cache mechanism to be more strick about the length of time it retians caches.
Docs to be updated to match soon, but TL;DR: Very strict 2hrs on the server, CDN is 4hrs (on /repo/ pages), up to 1 year (for /cdn/ pages)

I'm leaving this open until I figure out a process for cache purge requests!

**Comment by schme16** [comment]
Further to the above: #63
