### ISSUE TITLE
Serves the wrong gist file

### ISSUE THREAD

**Issue by Buntelrus** [schme16/gitcdn.xyz#61]
I have a gist with 2 files. 
I pasted `ttps://gist.githubusercontent.com/Buntelrus/1508cb9c1de48da29c03a9b278042697/raw/pdf.worker.bundle.js` the raw url of my gist file and got `https://gitcdn.link/repo/Buntelrus/1508cb9c1de48da29c03a9b278042697/raw/pdf.worker.bundle.js` to use.

But it seems that the other file of this gist is served.

**Comment by schme16** [comment]
Gists aren't totally supported, but will be in the 2.0.0 milestone update

**Comment by schme16** [comment]
Looks like this might have been a two fold issue.
 - The first is that it seems like the raw url you passed was incomplete, and should ahve looked more like this: `https://gist.githubusercontent.com/Buntelrus/1508cb9c1de48da29c03a9b278042697/raw/3cd57ec73d210e40b18a9e01cfecebccbf634be7/pdf.worker.js`
 - The second was that even IF it was sent correctly, some gists were being sent to an incorrect cdn/repo destination.

The first one is sorted by getting the correct raw link (found on the gist file's page)
The second has been taken care of on the server side.

**Comment by Buntelrus** [comment]
I passed the url correctly. If you don't specify a commit it means the latest.

**Comment by schme16** [comment]
Are you able to post a working gist link for me to test with?
The one posted in the first comment doesn't work when visited directly, let alone then put through the cdn.

**Comment by Buntelrus** [comment]
https://gist.githubusercontent.com/Buntelrus/1508cb9c1de48da29c03a9b278042697/raw/pdf.worker.js

I changed the file name. This Link works. You can just delete the hash between `raw` and `filename` and its serves the latest version.

**Comment by schme16** [comment]
Thanks for providing a live link, really help me track the issue!
Should be all sorted out in prod now. 
Can I ask you to do a few tests (try a couple of gists for me please)?

I'll leave this open until I hear back!

**Comment by Buntelrus** [comment]
Yeah I can confirm that I now get the correct file 👍. Well done! It's not likely that the file will change soon or often. Therefore caching is not an issue. But it would be nice, if there where a button to purge a file manually, if it becomes necessary.

**Comment by schme16** [comment]
Great to hear! 
And don't worry, a purge cache button is on it's way! (I should probably go make an issue for people to track: #63 )
