### ISSUE TITLE
File extension sometimes changed to .bin

### ISSUE THREAD

**Issue by warbe-maker** [schme16/gitcdn.xyz#62]
Enthusiastic in the first place unfortunately I have an issue. It appears unpredictable but some file extensions are changed to .bin and some not.
.frm (an exported VBA UserForm) was kept but .frx (the exported VBA UserForm's Design) was changed to .bin. A day before .bas (an exported  VBA module) was also changed to .bin.
It would be great if this unpredictability can be solved.

**Comment by schme16** [comment]
I'm not far from doing a pretty major overhaul of the back end. I'll add this to the list of todos.

Thanks for reporting it!

**Comment by warbe-maker** [comment]
Thanks for this reply. It appears that this extension problem is bound to my Android smartphone where I observed it. When using Windows (which is the target environment for all my posts and repos since the are all about Microsoft VBA) everything is fine so far. So there's no real urgency for this issue - in case it's one.

Best regards,
Walter
-- 
 Sicher gesendet mit Tutanota. Hol dir deine eigene verschlüsselte & werbefreie Mailbox: 
 https://tutanota.com


10. Okt. 2020, 04:09 von notifications@github.com:

**Comment by schme16** [comment]
Looking into this issue it seems that the likely casue is that I set the charset to utf-8 on a few specific filestypes (`.js`, `.json` `.css`, `.html`, `.txt`) as it helps rendering those files on non-mobile browsers.
Strangely **on** mobile browsers it seems to cause some issues (only when accessing the file directly, in a script tag/style tag, etc, it works as intended), on Android Browser (not sure if Chrome for Android is affected too, but maybe?) it appends a .bin to the filename, and forces it to be downloaded.

I'll keep hunting around for a way to make both platforms happy!
