### ISSUE TITLE
git CDN

### ISSUE THREAD

**Issue by hamdan-Deb** [schme16/gitcdn.xyz#69]
gitCDN.link works amazing. 

But, whenever i put my raw-gitHub link in gitcdn.xyz, It gives error which says "Not Found"

**Comment by hamdan-Deb** [comment]
Raw Link as an Example:  Try it on .link and .xyz domains of GiTCDN.

https://raw.githubusercontent.com/hamdan-Deb/hamdan-Deb.github.io/main/BaekrrClothing/productThumbnails/Bedding/Bedsheets-Images/Nishat-duck-BlackTan.png

**Comment by vednig** [comment]
See: https://gitcdn.link/repo/hamdan-Deb/hamdan-Deb.github.io/main/BaekrrClothing/productThumbnails/Bedding/Bedsheets-Images/Nishat-duck-BlackTan.png

**Comment by hamdan-Deb** [comment]
Cool, but why its not working on Gitcdn.XYZ  
thanks

**Comment by vednig** [comment]
It is try: https://gitcdn.xyz/repo/hamdan-Deb/hamdan-Deb.github.io/main/BaekrrClothing/productThumbnails/Bedding/Bedsheets-Images/Nishat-duck-BlackTan.png
