### ISSUE TITLE
Blacklisted 

### ISSUE THREAD

**Issue by Yerren** [schme16/gitcdn.xyz#72]
Hi there,

First off, thanks for this service, it's really helpful!

A couple of my files have been blacklisted, and I am unsure why. In particular:
https://gitcdn.xyz/cdn/Yerren/FreshWDL/master/js_bundles/moment.min.js and https://gitcdn.xyz/cdn/Yerren/FreshWDL/master/UpperContent.js

Please let me know where I have done wrong, and if I can do anything to resolve the issue.

Many thanks in advance!

**Comment by schme16** [comment]
Not sure what triggered these items to get temp blacklisted, bit they've been removed from the list now.

I can't find anything in the logs that shows anything you've done to be wrong, so all good!

**Comment by Yerren** [comment]
That's great, thank you very much!

**Comment by schme16** [comment]
No problem, sorry for the trouble!
