### ISSUE TITLE
Minification

### ISSUE THREAD

**Issue by vednig** [schme16/gitcdn.xyz#73]
Add on-the-fly minification of js and css files.
Such as in https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.5.13/clipboard.min.js
Automatically minifies a file if its minified version is unavailable in the repo.

**Comment by schme16** [comment]
You're in luck!
when you get your cdn link, e.g.: https://gitcdn.xyz/cdn/jquery/jquery/b2bbaa36d4d37bd48f954ed3cdbd50d3461a523d/build/release/dist.js
you can just add `min.` to the front and get a minified version: https://min.gitcdn.link/cdn/jquery/jquery/b2bbaa36d4d37bd48f954ed3cdbd50d3461a523d/build/release/dist.js

**Comment by vednig** [comment]
And any things to remember if using in production?

**Comment by vednig** [comment]
'Cause I'm redesigning the website at [cdn-git.herokuapp.com](cdn-git.herokuapp.com). If anything you need to add? tell me.
