### ISSUE TITLE
Redirected to incorrect commit

### ISSUE THREAD

**Issue by arctelix** [schme16/gitcdn.xyz#8]
I just pushed a new commit to my project where i changed the source file directory and i am getting directed to an old commit with "404: Not Found":

**old raw url** : https://raw.githubusercontent.com/arctelix/drag-resize-snap/master/drs.js
**new raw url** : https://raw.githubusercontent.com/arctelix/drag-resize-snap/master/dist/drs.js

The link generated from **new raw url** :
https://gitcdn.xyz/repo/arctelix/drag-resize-snap/master/dist/drs.js

Redirects to this commit and i get a  "404: Not Found":
https://cdn.gitcdn.link/cdn/arctelix/drag-resize-snap/dc4a39f3189680e6f8188e0d08ff2d52e05a12d5/dist/drs.js

If i manually enter the latest commit it works just fine:
https://cdn.gitcdn.link/cdn/arctelix/drag-resize-snap/f301bfcc65b4bd9a4e6746ff59beee2b264f6374/dist/drs.js

**The following urls do correctly redirect to the proper commit**
https://cdn.gitcdn.link/repo/arctelix/drag-resize-snap/master/dist/drs.js
https://cdn.gitcdn.link/repo/arctelix/drag-resize-snap/v0.1.1/dist/drs.js

Is the `https://gitcdn.xyz/repo/` endpoint no longer correct? 
Should we be using `https://cdn.gitcdn.link/repo/` instead?

Thanks for your awesome service!!

**Comment by schme16** [comment]
I'll look into it for you! Occasionally my CDN (Cloudflare) becomes a
little zealous in caching old artefacts, I'll clear that now, let me know
if the problem persists further.

**Comment by arctelix** [comment]
Thanks, just out of curiosity is there anything wrong with using the `https://cdn.gitcdn.link/repo/` endpoint?

**Comment by schme16** [comment]
definitely not, I'd encourage it really, you just have lower total cache
hits than with direct cdn endpoints, thats all

**Comment by schme16** [comment]
Looks like the issue was with my github commit cache becoming corrupt, a did a purge and everything seems to be going well. I might make a change that datestamps things a little better and refuses to use ones that are (n)seconds old. Great catch of an obscure issue!
